/* ============================================================
   SKETCHY!  —  card deck
   Channels: text · email · package · marketplace · bank · job
   answer:  'sketchy' (scam) | 'legit' (safe)
   hl:      one short phrase to highlight on the card (the "hook").
            Present on BOTH legit & sketchy cards so it never reveals
            the answer.
   ============================================================ */

export const CHANNEL_LABEL = {
  text: 'Text Message',
  email: 'Email',
  package: 'Package Alert',
  marketplace: 'Marketplace',
  bank: 'Bank Alert',
  job: 'Job Offer',
}

export const CARDS = [
  /* ---- showcase bank example (from brief) ---- */
  {
    id: 1,
    channel: 'bank',
    from: 'Your Bank',
    text: "Hey, it's your bank. We noticed suspicious activity. Verify your account now to avoid suspension.",
    hl: 'suspicious activity',
    answer: 'sketchy',
    why: 'Urgent “verify now or lose access” warnings are bait to rush you into a fake login.',
  },

  /* ---- the 5 brief examples (verbatim) ---- */
  {
    id: 2,
    channel: 'package',
    from: 'USPS Tracking',
    text: 'USPS: Your package could not be delivered. Confirm your address here: bit.ly/package-help',
    hl: 'bit.ly/package-help',
    answer: 'sketchy',
    why: 'Short links and urgent package warnings are classic scam bait.',
  },
  {
    id: 3,
    channel: 'text',
    from: 'Bright Smile Dental',
    text: 'Your dentist appointment is tomorrow at 2 PM. Reply C to confirm.',
    hl: 'tomorrow at 2 PM',
    answer: 'legit',
    why: "Simple appointment reminders are usually fine when they don't ask for money or passwords.",
  },
  {
    id: 4,
    channel: 'job',
    from: 'TalentHub Recruiting',
    text: "Remote job offer: We'll mail you a check to buy your work equipment.",
    hl: 'mail you a check',
    answer: 'sketchy',
    why: 'Fake check scams often hide inside remote job offers.',
  },
  {
    id: 5,
    channel: 'bank',
    from: 'Account Security',
    text: 'Your bank needs your password to verify recent activity.',
    hl: 'your password',
    answer: 'sketchy',
    why: 'A real bank will never ask for your password by text or email.',
  },
  {
    id: 6,
    channel: 'email',
    from: 'City Library',
    text: 'Your library book is due tomorrow. Renew through your account.',
    hl: 'due tomorrow',
    answer: 'legit',
    why: 'Low-pressure reminders from known services can be normal.',
  },

  /* ---- more, same spirit ---- */
  {
    id: 7,
    channel: 'package',
    from: 'Amazon',
    text: 'Your order #112‑4459 has shipped. Track it any time in the Amazon app.',
    hl: 'in the Amazon app',
    answer: 'legit',
    why: 'A shipping update with no link asking for info is just a normal notification.',
  },
  {
    id: 8,
    channel: 'text',
    from: 'Rewards Center',
    text: "You've WON a $1,000 gift card! Claim it now before it expires: clik.ly/win-now",
    hl: 'before it expires',
    answer: 'sketchy',
    why: 'Surprise prizes you never entered for are bait — especially with a countdown and a short link.',
  },
  {
    id: 9,
    channel: 'email',
    from: 'Sarah · Accounting',
    text: "Hey, it's the CEO. I'm in a meeting — quietly grab 5 gift cards and text me the codes. Reimburse you later.",
    hl: 'text me the codes',
    answer: 'sketchy',
    why: '“Boss needs gift cards, keep it secret” is one of the most common workplace scams.',
  },
  {
    id: 10,
    channel: 'email',
    from: 'Netflix',
    text: 'Your payment failed. Update your card in the next 24h or your account will be deleted: netflix-billing.co',
    hl: 'netflix-billing.co',
    answer: 'sketchy',
    why: "Real companies don't threaten instant deletion — and that domain is fake.",
  },
  {
    id: 11,
    channel: 'email',
    from: 'City Power & Light',
    text: 'Your electric bill of $84.20 is due June 15. Pay in your account or by mail. No rush.',
    hl: 'No rush',
    answer: 'legit',
    why: 'A calm bill reminder with normal payment options and no scary link is routine.',
  },
  {
    id: 12,
    channel: 'bank',
    from: 'IRS Notice',
    text: 'FINAL NOTICE: Pay $2,400 in gift cards today or a warrant will be issued for your arrest.',
    hl: 'in gift cards',
    answer: 'sketchy',
    why: 'The IRS never demands gift cards or threatens arrest by text. Ever.',
  },
  {
    id: 13,
    channel: 'text',
    from: 'Unknown Number',
    text: "Hey it's Mike! Lost my phone, this is my new number. Can you send me $200? I'll pay you back tonight.",
    hl: 'send me $200',
    answer: 'sketchy',
    why: "“It's me, new number, send money fast” is a classic impersonation trick. Call the real Mike first.",
  },
  {
    id: 14,
    channel: 'text',
    from: "Dr. Lee's Office",
    text: 'Your appointment with Dr. Lee is confirmed for Thursday at 10 AM. Call us to reschedule.',
    hl: 'Call us to reschedule',
    answer: 'legit',
    why: 'A confirmation that only asks you to call the office is low‑risk and normal.',
  },
  {
    id: 15,
    channel: 'marketplace',
    from: 'Buyer · Couch listing',
    text: "I'll take the couch! I'll send extra to cover my mover — just refund me the difference after.",
    hl: 'refund me the difference',
    answer: 'sketchy',
    why: "Overpayment + “refund the difference” is a money trap. Their payment will bounce, yours won't.",
  },
  {
    id: 16,
    channel: 'marketplace',
    from: 'Buyer · Bike listing',
    text: 'Hi! Is the bike still available? Could I come pick it up on Saturday morning?',
    hl: 'pick it up on Saturday',
    answer: 'legit',
    why: 'A buyer asking normal questions and offering to meet in person is just a buyer.',
  },
  {
    id: 17,
    channel: 'email',
    from: 'Apple Support',
    text: 'Your Apple ID was locked for security. Verify your identity now: apple-id-secure.co',
    hl: 'apple-id-secure.co',
    answer: 'sketchy',
    why: "That's not an Apple address. “Verify now” links lead to fake login pages that steal passwords.",
  },
  {
    id: 18,
    channel: 'email',
    from: 'Costco Membership',
    text: 'Your membership renews next month at your current rate. No action needed.',
    hl: 'No action needed',
    answer: 'legit',
    why: '“No action needed” with no link or payment request is exactly what a real notice looks like.',
  },
  {
    id: 19,
    channel: 'bank',
    from: 'QuickLoan',
    text: "Congrats — you're pre‑approved! Just pay a $99 processing fee to release your $5,000 loan.",
    hl: '$99 processing fee',
    answer: 'sketchy',
    why: 'Real lenders take fees out of the loan. Paying upfront to “release” money is the scam.',
  },
  {
    id: 20,
    channel: 'text',
    from: '2‑Factor Code',
    text: "Your verification code is 884213. Don't share this code with anyone.",
    hl: "Don't share this code",
    answer: 'legit',
    why: 'A code you requested is normal — the scam is when someone calls asking you to read it out.',
  },
  {
    id: 21,
    channel: 'email',
    from: 'PayPal',
    text: 'Someone sent you $500! Click to accept before it expires: pay-pal.cash/claim',
    hl: 'pay-pal.cash/claim',
    answer: 'sketchy',
    why: "You don't “claim” money you weren't expecting through a sketchy look‑alike link.",
  },
  {
    id: 22,
    channel: 'text',
    from: 'Food Delivery',
    text: 'Your order is 5 minutes away! Track your driver live in the app.',
    hl: 'in the app',
    answer: 'legit',
    why: 'A delivery update that points you back to the app you ordered from is fine.',
  },
  {
    id: 23,
    channel: 'email',
    from: 'Walmart Rewards',
    text: 'SHOPPER SELECTED: Claim your FREE $750 reward — just finish this quick 3‑question survey!',
    hl: 'FREE $750 reward',
    answer: 'sketchy',
    why: '“Free reward, just take this survey” funnels you toward handing over personal info.',
  },
  {
    id: 24,
    channel: 'text',
    from: 'Lincoln Elementary',
    text: 'Reminder: early dismissal tomorrow at 1 PM due to the weather forecast.',
    hl: 'early dismissal tomorrow',
    answer: 'legit',
    why: 'An informational alert from a school you know, with nothing to click or pay, is normal.',
  },
  {
    id: 25,
    channel: 'text',
    from: 'Crypto Coach',
    text: 'Double your Bitcoin in 24 hours! Send to this wallet to start earning today.',
    hl: 'Double your Bitcoin',
    answer: 'sketchy',
    why: "Guaranteed doubling is impossible. Send crypto to a stranger and it's just gone.",
  },
  {
    id: 26,
    channel: 'email',
    from: 'Spotify',
    text: "Here's your receipt — Premium, $10.99. Manage your plan any time in Account settings.",
    hl: 'Account settings',
    answer: 'legit',
    why: 'A receipt for a subscription you actually have, pointing to your own settings, is routine.',
  },

  /* ---- batch 2: 50-card deck. Trickier (but fair) legit cards. ---- */
  {
    id: 27,
    channel: 'text',
    from: 'Verizon',
    text: 'Your bill is overdue. Avoid service cutoff today — pay here: vzw-secure-pay.com',
    hl: 'vzw-secure-pay.com',
    answer: 'sketchy',
    why: 'Real carriers send you to their official app or site, not a look‑alike pay link.',
  },
  {
    id: 28,
    channel: 'email',
    from: 'DocuSign',
    text: 'You have a document to sign. Review and verify your login first: docusign-verify.net',
    hl: 'docusign-verify.net',
    answer: 'sketchy',
    why: '“Verify your login” plus an odd domain is the tell — open the real site directly.',
  },
  {
    id: 29,
    channel: 'text',
    from: 'Toll Service',
    text: 'You have an unpaid toll of $6.99. Pay now to avoid a $50 late fee: ezpass-toll.info',
    hl: 'ezpass-toll.info',
    answer: 'sketchy',
    why: 'Toll‑by‑text scams pair a tiny fee with a big threat and a fake domain.',
  },
  {
    id: 30,
    channel: 'marketplace',
    from: 'Buyer · Phone listing',
    text: "I'll buy it now! Send me your Venmo and I'll Zelle the deposit, then you ship first.",
    hl: 'ship first',
    answer: 'sketchy',
    why: 'Ship‑first, mixed‑app payment requests are how marketplace buyers vanish with your item.',
  },
  {
    id: 31,
    channel: 'job',
    from: 'HR · Remote Co',
    text: "You're hired! Send a photo of your ID and your bank login so we can set up payroll.",
    hl: 'bank login',
    answer: 'sketchy',
    why: 'No employer needs your bank login. Payroll uses account numbers, never your password.',
  },
  {
    id: 32,
    channel: 'email',
    from: 'Microsoft 365',
    text: "Unusual sign‑in detected. Confirm it's you in 15 minutes or your mailbox locks: m365-alert.co",
    hl: '15 minutes',
    answer: 'sketchy',
    why: 'A countdown plus a fake domain means phishing. Real alerts live inside your account.',
  },
  {
    id: 33,
    channel: 'text',
    from: 'Amazon',
    text: 'Your account is on hold. Verify your payment to release your recent order: amzn-billing.help',
    hl: 'amzn-billing.help',
    answer: 'sketchy',
    why: "Amazon won't text you a billing link from a random look‑alike domain.",
  },
  {
    id: 34,
    channel: 'bank',
    from: 'Chase Alert',
    text: "Did you spend $812 at BestBuy? Reply NO and we'll text you a link to lock your card.",
    hl: 'text you a link',
    answer: 'sketchy',
    why: 'A real fraud alert tells you to call the number on your card — not to tap a texted link.',
  },
  {
    id: 35,
    channel: 'email',
    from: 'Google',
    text: 'Your storage is full! Reactivate now with a one‑time $1.99 verification charge: g-storage.co',
    hl: '$1.99 verification charge',
    answer: 'sketchy',
    why: 'A “tiny verification charge” is a trick to capture your card. Google never does this.',
  },
  {
    id: 36,
    channel: 'text',
    from: 'Unknown Number',
    text: "Grandma, I'm in trouble and need $500 for bail. Please don't tell mom and dad.",
    hl: "don't tell mom and dad",
    answer: 'sketchy',
    why: 'Secrecy plus urgent money is the grandparent scam. Hang up and call them directly.',
  },
  {
    id: 37,
    channel: 'email',
    from: 'LinkedIn',
    text: 'A recruiter wants you! Unlock the offer by paying a $15 background-check fee.',
    hl: '$15 background-check fee',
    answer: 'sketchy',
    why: 'Legit recruiters never charge you an upfront fee to “unlock” a job.',
  },
  {
    id: 38,
    channel: 'text',
    from: 'Bank of America',
    text: 'ALERT: your account is suspended. Restore access immediately: bofa-secure-login.com',
    hl: 'bofa-secure-login.com',
    answer: 'sketchy',
    why: '“Suspended — click to restore” with a look‑alike domain is classic bank phishing.',
  },

  {
    id: 39,
    channel: 'bank',
    from: 'Chase',
    text: 'We blocked a $640 charge we flagged as fraud. If this was you, reply YES or call the number on your card.',
    hl: 'call the number on your card',
    answer: 'legit',
    why: "It points you to the number on your card and asks for no secrets — that's how a real alert behaves.",
  },
  {
    id: 40,
    channel: 'email',
    from: 'IRS.gov',
    text: 'Your tax refund has been processed. Track its status any time at irs.gov/refunds.',
    hl: 'irs.gov/refunds',
    answer: 'legit',
    why: 'It points to the real .gov site, asks for nothing, and makes no threats — a normal update.',
  },
  {
    id: 41,
    channel: 'package',
    from: 'UPS',
    text: 'Your delivery needs a signature. Pick a new date in the UPS app or at ups.com.',
    hl: 'in the UPS app',
    answer: 'legit',
    why: 'It sends you to the official app or site with no fee and no login link — routine.',
  },
  {
    id: 42,
    channel: 'email',
    from: 'PayPal',
    text: "You sent $24.00 to Corner Coffee. Didn't make this? Report it from your PayPal Activity page.",
    hl: 'PayPal Activity page',
    answer: 'legit',
    why: 'A receipt that points back to your own account page, with no link to click, is normal.',
  },
  {
    id: 43,
    channel: 'bank',
    from: 'Wells Fargo',
    text: 'Your monthly statement is ready. View it by signing in at wellsfargo.com or in the app.',
    hl: 'wellsfargo.com',
    answer: 'legit',
    why: '“Statement ready, sign in normally” with the real domain and no urgency is routine.',
  },
  {
    id: 44,
    channel: 'text',
    from: "Doctor's Office",
    text: 'Your lab results are in. Log in to the patient portal to view them.',
    hl: 'patient portal',
    answer: 'legit',
    why: 'Health updates that send you to log in normally, with nothing to pay, are standard.',
  },
  {
    id: 45,
    channel: 'email',
    from: 'United Airlines',
    text: 'Check‑in for flight UA482 opens in 24 hours. Check in on the app or at the airport.',
    hl: 'opens in 24 hours',
    answer: 'legit',
    why: 'A travel reminder with normal options and nothing to “verify” or pay is fine.',
  },
  {
    id: 46,
    channel: 'text',
    from: 'Corner Pharmacy',
    text: 'Your prescription is ready for pickup at the Main St location.',
    hl: 'ready for pickup',
    answer: 'legit',
    why: 'A simple pickup notice that asks for nothing is routine.',
  },
  {
    id: 47,
    channel: 'email',
    from: 'City Utilities',
    text: 'Scheduled maintenance may interrupt power on June 12, 1–3 PM. No action needed.',
    hl: 'Scheduled maintenance',
    answer: 'legit',
    why: 'An informational notice with a specific window and nothing to click is normal.',
  },
  {
    id: 48,
    channel: 'text',
    from: 'Your Bank',
    text: 'Your one‑time code is 503118. We will never ask you to share it.',
    hl: 'never ask you to share it',
    answer: 'legit',
    why: 'Codes you requested are normal — the scam is anyone asking you to read it aloud.',
  },
  {
    id: 49,
    channel: 'email',
    from: 'School District',
    text: 'Report cards are now available in the parent portal.',
    hl: 'parent portal',
    answer: 'legit',
    why: 'Pointing you to a portal you already use, with nothing to buy, is routine.',
  },
  {
    id: 50,
    channel: 'marketplace',
    from: 'Buyer · Desk listing',
    text: 'Still available? I can pay cash on pickup tomorrow afternoon if that works.',
    hl: 'cash on pickup',
    answer: 'legit',
    why: 'Cash on local pickup and normal questions — a real buyer.',
  },

  /* ---- batch 3: deck expansion (51–75). More nuanced legit cards that look
         risky at first glance, plus more scam variety across categories. ---- */
  {
    id: 51,
    channel: 'bank',
    from: 'Wells Fargo',
    text: 'Your January statement is ready. Sign in at the address on the back of your card to view it.',
    hl: 'on the back of your card',
    answer: 'legit',
    why: "It points you to the site printed on your own card — not a link in the message. That's the safe way in.",
  },
  {
    id: 52,
    channel: 'email',
    from: 'Microsoft account',
    text: "Your password was changed successfully. Didn't do this? Open your account from your own bookmark and review activity.",
    hl: 'your own bookmark',
    answer: 'legit',
    why: 'It tells you to reach your account the way you normally do, instead of handing you a link to click.',
  },
  {
    id: 53,
    channel: 'package',
    from: 'USPS',
    text: 'Your package is out for delivery today. Track it in the USPS app or at usps.com — no fees due.',
    hl: 'no fees due',
    answer: 'legit',
    why: 'Official app, a real domain, and nothing to pay — a normal delivery update.',
  },
  {
    id: 54,
    channel: 'bank',
    from: 'Chase',
    text: 'A new device signed in using your passkey. If this was you, no action is needed.',
    hl: 'no action is needed',
    answer: 'legit',
    why: 'A heads-up about something you just did, with nothing to click or confirm, is routine.',
  },
  {
    id: 55,
    channel: 'email',
    from: 'TurboTax',
    text: 'Your e-file was accepted by the IRS. View your return any time by signing in to TurboTax.',
    hl: 'signing in to TurboTax',
    answer: 'legit',
    why: 'A status update that sends you to sign in normally, with no link or payment, is fine.',
  },
  {
    id: 56,
    channel: 'package',
    from: 'FedEx',
    text: 'We missed you. Schedule a free redelivery in the FedEx app — there is no fee to reschedule.',
    hl: 'no fee to reschedule',
    answer: 'legit',
    why: 'Real redelivery is free and handled in the official app; scam versions invent a small fee.',
  },
  {
    id: 57,
    channel: 'job',
    from: 'Acme Corp · HR',
    text: 'Your interview is confirmed for Tuesday at 10 AM. Reply to this email to reschedule.',
    hl: 'confirmed for Tuesday',
    answer: 'legit',
    why: 'A confirmation that only asks you to reply, with no fee or documents, is normal.',
  },
  {
    id: 58,
    channel: 'email',
    from: 'Adobe',
    text: 'Receipt: Creative Cloud, $19.99. Manage or cancel your plan any time in your account.',
    hl: 'Manage or cancel',
    answer: 'legit',
    why: 'A receipt for a plan you actually have, pointing to your own account with no urgency, is routine.',
  },
  {
    id: 59,
    channel: 'bank',
    from: 'Capital One',
    text: 'Heads up: your statement balance of $212.40 is due June 20. Pay in the app or online.',
    hl: 'due June 20',
    answer: 'legit',
    why: 'A calm payment reminder with normal options and no link to tap is just a notice.',
  },
  {
    id: 60,
    channel: 'text',
    from: 'Delta',
    text: 'Flight DL55 is now boarding at gate C12. Have your boarding pass ready in the app.',
    hl: 'in the app',
    answer: 'legit',
    why: "A travel update pointing back to the airline's own app, asking for nothing, is fine.",
  },
  {
    id: 61,
    channel: 'email',
    from: 'County Clerk',
    text: 'Jury duty reminder: report Monday at 8 AM. Bring the summons you received by mail.',
    hl: 'received by mail',
    answer: 'legit',
    why: 'It references the official mailed summons and asks for no payment or personal data — normal.',
  },
  {
    id: 62,
    channel: 'text',
    from: 'MyChart',
    text: 'A new lab result is available. Log in to the patient portal you already use to view it.',
    hl: 'already use',
    answer: 'legit',
    why: 'Health updates that send you to a portal you set up yourself, with nothing to buy, are standard.',
  },
  {
    id: 63,
    channel: 'marketplace',
    from: 'Buyer · Guitar listing',
    text: 'Is this still available? Happy to meet at the coffee shop on 5th and pay cash.',
    hl: 'pay cash',
    answer: 'legit',
    why: 'Normal questions plus a public meetup and cash — a real local buyer.',
  },
  {
    id: 64,
    channel: 'email',
    from: 'HOA',
    text: 'Reminder: community meeting this Thursday at 7 PM in the clubhouse. No RSVP needed.',
    hl: 'No RSVP needed',
    answer: 'legit',
    why: 'An informational notice with a time and place and nothing to click is normal.',
  },
  {
    id: 65,
    channel: 'package',
    from: 'FedEx',
    text: 'Your parcel is on hold. Pay a $2.99 redelivery fee now: fedex-redeliver.com',
    hl: 'fedex-redeliver.com',
    answer: 'sketchy',
    why: 'Redelivery is free in the real app; a small fee plus a look-alike domain is the scam.',
  },
  {
    id: 66,
    channel: 'email',
    from: 'Mail Admin',
    text: 'Your mailbox is over quota and will be disabled. Revalidate within 24 hours: mail-quota-fix.com',
    hl: 'mail-quota-fix.com',
    answer: 'sketchy',
    why: 'Quota threats with a countdown and an odd domain are phishing for your login.',
  },
  {
    id: 67,
    channel: 'text',
    from: 'Unknown Number',
    text: "Mom, my phone broke and I'm on a friend's. Can you send money for the repair today?",
    hl: 'send money',
    answer: 'sketchy',
    why: 'A "new number" relative urgently asking for money is the family-impersonation scam. Call them first.',
  },
  {
    id: 68,
    channel: 'marketplace',
    from: 'Buyer · Sofa listing',
    text: "I'll send a courier and overpay for your trouble — just send the extra back in gift cards.",
    hl: 'in gift cards',
    answer: 'sketchy',
    why: 'Overpay-and-refund, especially in gift cards, is a classic marketplace money trap.',
  },
  {
    id: 69,
    channel: 'bank',
    from: 'Zelle Support',
    text: 'To reverse the fraudulent $750 transfer, send the same amount back to yourself here: zelle-reverse.com',
    hl: 'zelle-reverse.com',
    answer: 'sketchy',
    why: "You can't “reverse” fraud by sending money — that link just steals a real payment.",
  },
  {
    id: 70,
    channel: 'job',
    from: 'Hiring Team',
    text: 'Mystery-shopper gig: deposit the check we send, wire us 80%, and keep the rest as pay.',
    hl: 'wire us 80%',
    answer: 'sketchy',
    why: 'Deposit-and-wire offers are fake-check scams — the check bounces after your wire is gone.',
  },
  {
    id: 71,
    channel: 'email',
    from: 'Geek Squad',
    text: 'Your subscription auto-renewed for $399.99. To cancel, call 1-800-555-0142 now.',
    hl: 'call 1-800-555-0142',
    answer: 'sketchy',
    why: 'Surprise renewal invoices with a "call to cancel" number are refund scams that talk you into paying.',
  },
  {
    id: 72,
    channel: 'bank',
    from: 'Card Services',
    text: 'We will deactivate your debit card tonight. Confirm your PIN to keep it active.',
    hl: 'Confirm your PIN',
    answer: 'sketchy',
    why: "No bank asks for your PIN — and never by text. That's theft bait.",
  },
  {
    id: 73,
    channel: 'text',
    from: 'IRS Refund',
    text: 'You have an unclaimed refund of $128.40. Claim it before it expires: irs-refund-portal.com',
    hl: 'irs-refund-portal.com',
    answer: 'sketchy',
    why: "The IRS doesn't text refund links, and that's not a .gov address.",
  },
  {
    id: 74,
    channel: 'package',
    from: 'Customs',
    text: 'Your international parcel is held. Pay the $3.50 import fee to release it: parcel-customs.co',
    hl: 'parcel-customs.co',
    answer: 'sketchy',
    why: 'A tiny "customs fee" on a look-alike domain is a card-skimming scam.',
  },
  {
    id: 75,
    channel: 'email',
    from: 'Coinbase',
    text: 'Suspicious withdrawal detected. Secure your wallet by confirming your seed phrase: coinbase-secure.co',
    hl: 'seed phrase',
    answer: 'sketchy',
    why: 'Never share a seed phrase — anyone who has it owns your crypto. Real exchanges never ask for it.',
  },

  /* ---- batch 4: deck expansion (76-100). More edge cases and safe notices
         that reward checking behavior, not just "does it have a link?" ---- */
  {
    id: 76,
    channel: 'bank',
    from: 'American Express',
    text: 'Card ending 1007 was used online for $94.18. If this was not you, open the Amex app and review alerts.',
    hl: 'open the Amex app',
    answer: 'legit',
    why: 'It asks you to use the official app instead of a message link, and it asks for no private info.',
  },
  {
    id: 77,
    channel: 'email',
    from: 'Dropbox',
    text: 'Your shared folder access changed. Review recent activity by signing in directly to dropbox.com.',
    hl: 'signing in directly',
    answer: 'legit',
    why: 'A security notice that tells you to go directly to the real site is safer than a tap-here link.',
  },
  {
    id: 78,
    channel: 'package',
    from: 'DHL',
    text: 'Delivery attempt scheduled for tomorrow. Manage delivery preferences in the DHL app.',
    hl: 'DHL app',
    answer: 'legit',
    why: 'Using the official app for delivery preferences is normal, and there is no surprise fee.',
  },
  {
    id: 79,
    channel: 'job',
    from: 'Greenline Studio',
    text: 'Thanks for applying. Your first interview is a video call; no documents are needed before the call.',
    hl: 'no documents are needed',
    answer: 'legit',
    why: 'A normal interview invite does not ask for bank details, ID photos, fees, or app installs.',
  },
  {
    id: 80,
    channel: 'marketplace',
    from: 'Seller · Camera listing',
    text: 'I can meet at the police station exchange zone at 3 PM and accept cash or Venmo in person.',
    hl: 'exchange zone',
    answer: 'legit',
    why: 'A public meetup and in-person payment are normal marketplace safety moves.',
  },
  {
    id: 81,
    channel: 'email',
    from: 'Venmo',
    text: 'You paid Jamie $18.00. If you do not recognize this, review your Venmo app activity.',
    hl: 'Venmo app activity',
    answer: 'legit',
    why: 'It points back to the app and avoids a cancel-or-refund link, which is what you want.',
  },
  {
    id: 82,
    channel: 'text',
    from: 'Water Utility',
    text: 'Boil-water advisory lifted for your area. Details are available at your city website.',
    hl: 'city website',
    answer: 'legit',
    why: 'A public safety update with no payment request or personal info ask is routine.',
  },
  {
    id: 83,
    channel: 'email',
    from: 'GitHub',
    text: 'A personal access token was added to your account. If this was not you, visit github.com/settings/security.',
    hl: 'github.com/settings/security',
    answer: 'legit',
    why: 'That is the real domain and a direct account-security path, with no password request in the message.',
  },
  {
    id: 84,
    channel: 'text',
    from: 'Library',
    text: 'A hold is ready for pickup. Bring your library card by Friday or the hold will expire.',
    hl: 'Bring your library card',
    answer: 'legit',
    why: 'A pickup reminder with a normal deadline and no payment link is safe.',
  },
  {
    id: 85,
    channel: 'bank',
    from: 'Credit Union',
    text: 'We noticed a login from a new browser. If this was not you, call the number printed on your debit card.',
    hl: 'printed on your debit card',
    answer: 'legit',
    why: 'Calling the number on your own card is a trusted path; the message does not ask you to click.',
  },
  {
    id: 86,
    channel: 'email',
    from: 'Norton Billing',
    text: 'Your $489.00 renewal is processing. Call this number within 30 minutes to cancel and receive a refund.',
    hl: 'within 30 minutes',
    answer: 'sketchy',
    why: 'Fake renewal notices use panic and a phone number to pull you into a refund scam.',
  },
  {
    id: 87,
    channel: 'text',
    from: 'Parking Notice',
    text: 'Unpaid parking invoice #P4471. Pay $4.20 today or penalties begin: city-parking-pay.com',
    hl: 'city-parking-pay.com',
    answer: 'sketchy',
    why: 'Tiny fines plus fake city payment domains are built to steal card details fast.',
  },
  {
    id: 88,
    channel: 'email',
    from: 'OneDrive Team',
    text: 'Your files will be deleted tonight. Login here to save your storage: onedrive-safe.net',
    hl: 'onedrive-safe.net',
    answer: 'sketchy',
    why: 'Threats about deletion plus a look-alike domain are phishing for your Microsoft login.',
  },
  {
    id: 89,
    channel: 'marketplace',
    from: 'Buyer · Laptop listing',
    text: "I'll pay full price, but my cousin will pick it up. Please email me a code from Zelle to prove you're real.",
    hl: 'code from Zelle',
    answer: 'sketchy',
    why: 'Verification codes are never proof for buyers; sharing one can let them hijack your payment account.',
  },
  {
    id: 90,
    channel: 'job',
    from: 'Data Entry HR',
    text: 'Before orientation, buy three $100 Apple cards so we can activate your employee software.',
    hl: 'Apple cards',
    answer: 'sketchy',
    why: 'Jobs never require gift cards to activate software. Gift cards are cash for scammers.',
  },
  {
    id: 91,
    channel: 'text',
    from: 'Medicare Help',
    text: 'Your Medicare benefits expire today. Send your SSN to keep coverage active.',
    hl: 'Send your SSN',
    answer: 'sketchy',
    why: 'Government benefits do not expire by text, and no legitimate office asks for your SSN that way.',
  },
  {
    id: 92,
    channel: 'email',
    from: 'Facebook Security',
    text: 'Your page violates copyright rules. Appeal now with your login here: meta-appeal-center.com',
    hl: 'meta-appeal-center.com',
    answer: 'sketchy',
    why: 'Fake policy appeals use fear and fake Meta domains to steal account logins.',
  },
  {
    id: 93,
    channel: 'bank',
    from: 'Fraud Department',
    text: 'To stop a wire transfer, move your money to a new safe account we created for you.',
    hl: 'safe account',
    answer: 'sketchy',
    why: 'There is no such thing as a bank-created safe account you must transfer into by text.',
  },
  {
    id: 94,
    channel: 'package',
    from: 'US Customs',
    text: 'Your package contains restricted goods. Pay the inspection bond now or police will be notified.',
    hl: 'police will be notified',
    answer: 'sketchy',
    why: 'Threats of police action plus instant payment demands are intimidation, not customs procedure.',
  },
  {
    id: 95,
    channel: 'email',
    from: 'Scholarship Office',
    text: 'Congratulations! Pay a $35 release fee today to receive your $2,000 scholarship.',
    hl: '$35 release fee',
    answer: 'sketchy',
    why: 'Real scholarships do not require release fees before sending award money.',
  },
  {
    id: 96,
    channel: 'text',
    from: 'Cash App',
    text: 'Cash App support: send us your sign-in code so we can remove a pending charge.',
    hl: 'sign-in code',
    answer: 'sketchy',
    why: 'Support teams never need your one-time code. Anyone asking for it is trying to take over your account.',
  },
  {
    id: 97,
    channel: 'email',
    from: 'Airbnb Host',
    text: 'Please cancel your booking and pay me directly by wire for a 20% discount.',
    hl: 'pay me directly',
    answer: 'sketchy',
    why: 'Moving off-platform removes protections and is a common rental scam setup.',
  },
  {
    id: 98,
    channel: 'text',
    from: 'Court Services',
    text: 'You missed jury duty. Pay $250 in prepaid cards today to avoid arrest.',
    hl: 'prepaid cards',
    answer: 'sketchy',
    why: 'Courts do not settle warrants with prepaid cards or text threats.',
  },
  {
    id: 99,
    channel: 'email',
    from: 'Instagram',
    text: 'Blue badge approved. Finish verification by entering your password at ig-badge-verify.com.',
    hl: 'ig-badge-verify.com',
    answer: 'sketchy',
    why: 'Verification scams use fake domains to steal creator accounts.',
  },
  {
    id: 100,
    channel: 'marketplace',
    from: 'Seller · Rental listing',
    text: 'The apartment is yours, but I am overseas. Wire the deposit first and I will mail the keys.',
    hl: 'mail the keys',
    answer: 'sketchy',
    why: 'Rental scams often ask for deposits before a tour, then promise to mail keys that never arrive.',
  },
]
