/* ============================================================
   SKETCHY!  —  card deck
   Channels: text · email · package · marketplace · bank · job
   answer:  'sketchy' (scam) | 'legit' (safe)
   hl:      one short phrase to highlight on the card (the "hook").
            Present on BOTH legit & sketchy cards so it never reveals
            the answer.
   ============================================================ */

export const CHANNEL_LABEL = {
  text: 'Text Message',
  email: 'Email',
  package: 'Package Alert',
  marketplace: 'Marketplace',
  bank: 'Bank Alert',
  job: 'Job Offer',
}

export const CARDS = [
  /* ---- showcase bank example (from brief) ---- */
  {
    id: 1,
    channel: 'bank',
    from: 'Your Bank',
    text: "Hey, it's your bank. We noticed suspicious activity. Verify your account now to avoid suspension.",
    hl: 'suspicious activity',
    answer: 'sketchy',
    why: 'Urgent “verify now or lose access” warnings are bait to rush you into a fake login.',
  },

  /* ---- the 5 brief examples (verbatim) ---- */
  {
    id: 2,
    channel: 'package',
    from: 'USPS Tracking',
    text: 'USPS: Your package could not be delivered. Confirm your address here: bit.ly/package-help',
    hl: 'bit.ly/package-help',
    answer: 'sketchy',
    why: 'Short links and urgent package warnings are classic scam bait.',
  },
  {
    id: 3,
    channel: 'text',
    from: 'Bright Smile Dental',
    text: 'Your dentist appointment is tomorrow at 2 PM. Reply C to confirm.',
    hl: 'tomorrow at 2 PM',
    answer: 'legit',
    why: "Simple appointment reminders are usually fine when they don't ask for money or passwords.",
  },
  {
    id: 4,
    channel: 'job',
    from: 'TalentHub Recruiting',
    text: "Remote job offer: We'll mail you a check to buy your work equipment.",
    hl: 'mail you a check',
    answer: 'sketchy',
    why: 'Fake check scams often hide inside remote job offers.',
  },
  {
    id: 5,
    channel: 'bank',
    from: 'Account Security',
    text: 'Your bank needs your password to verify recent activity.',
    hl: 'your password',
    answer: 'sketchy',
    why: 'A real bank will never ask for your password by text or email.',
  },
  {
    id: 6,
    channel: 'email',
    from: 'City Library',
    text: 'Your library book is due tomorrow. Renew through your account.',
    hl: 'due tomorrow',
    answer: 'legit',
    why: 'Low-pressure reminders from known services can be normal.',
  },

  /* ---- more, same spirit ---- */
  {
    id: 7,
    channel: 'package',
    from: 'Amazon',
    text: 'Your order #112‑4459 has shipped. Track it any time in the Amazon app.',
    hl: 'in the Amazon app',
    answer: 'legit',
    why: 'A shipping update with no link asking for info is just a normal notification.',
  },
  {
    id: 8,
    channel: 'text',
    from: 'Rewards Center',
    text: "You've WON a $1,000 gift card! Claim it now before it expires: clik.ly/win-now",
    hl: 'before it expires',
    answer: 'sketchy',
    why: 'Surprise prizes you never entered for are bait — especially with a countdown and a short link.',
  },
  {
    id: 9,
    channel: 'email',
    from: 'Sarah · Accounting',
    text: "Hey, it's the CEO. I'm in a meeting — quietly grab 5 gift cards and text me the codes. Reimburse you later.",
    hl: 'text me the codes',
    answer: 'sketchy',
    why: '“Boss needs gift cards, keep it secret” is one of the most common workplace scams.',
  },
  {
    id: 10,
    channel: 'email',
    from: 'Netflix',
    text: 'Your payment failed. Update your card in the next 24h or your account will be deleted: netflix-billing.co',
    hl: 'netflix-billing.co',
    answer: 'sketchy',
    why: "Real companies don't threaten instant deletion — and that domain is fake.",
  },
  {
    id: 11,
    channel: 'email',
    from: 'City Power & Light',
    text: 'Your electric bill of $84.20 is due June 15. Pay in your account or by mail. No rush.',
    hl: 'No rush',
    answer: 'legit',
    why: 'A calm bill reminder with normal payment options and no scary link is routine.',
  },
  {
    id: 12,
    channel: 'bank',
    from: 'IRS Notice',
    text: 'FINAL NOTICE: Pay $2,400 in gift cards today or a warrant will be issued for your arrest.',
    hl: 'in gift cards',
    answer: 'sketchy',
    why: 'The IRS never demands gift cards or threatens arrest by text. Ever.',
  },
  {
    id: 13,
    channel: 'text',
    from: 'Unknown Number',
    text: "Hey it's Mike! Lost my phone, this is my new number. Can you send me $200? I'll pay you back tonight.",
    hl: 'send me $200',
    answer: 'sketchy',
    why: "“It's me, new number, send money fast” is a classic impersonation trick. Call the real Mike first.",
  },
  {
    id: 14,
    channel: 'text',
    from: "Dr. Lee's Office",
    text: 'Your appointment with Dr. Lee is confirmed for Thursday at 10 AM. Call us to reschedule.',
    hl: 'Call us to reschedule',
    answer: 'legit',
    why: 'A confirmation that only asks you to call the office is low‑risk and normal.',
  },
  {
    id: 15,
    channel: 'marketplace',
    from: 'Buyer · Couch listing',
    text: "I'll take the couch! I'll send extra to cover my mover — just refund me the difference after.",
    hl: 'refund me the difference',
    answer: 'sketchy',
    why: "Overpayment + “refund the difference” is a money trap. Their payment will bounce, yours won't.",
  },
  {
    id: 16,
    channel: 'marketplace',
    from: 'Buyer · Bike listing',
    text: 'Hi! Is the bike still available? Could I come pick it up on Saturday morning?',
    hl: 'pick it up on Saturday',
    answer: 'legit',
    why: 'A buyer asking normal questions and offering to meet in person is just a buyer.',
  },
  {
    id: 17,
    channel: 'email',
    from: 'Apple Support',
    text: 'Your Apple ID was locked for security. Verify your identity now: apple-id-secure.co',
    hl: 'apple-id-secure.co',
    answer: 'sketchy',
    why: "That's not an Apple address. “Verify now” links lead to fake login pages that steal passwords.",
  },
  {
    id: 18,
    channel: 'email',
    from: 'Costco Membership',
    text: 'Your membership renews next month at your current rate. No action needed.',
    hl: 'No action needed',
    answer: 'legit',
    why: '“No action needed” with no link or payment request is exactly what a real notice looks like.',
  },
  {
    id: 19,
    channel: 'bank',
    from: 'QuickLoan',
    text: "Congrats — you're pre‑approved! Just pay a $99 processing fee to release your $5,000 loan.",
    hl: '$99 processing fee',
    answer: 'sketchy',
    why: 'Real lenders take fees out of the loan. Paying upfront to “release” money is the scam.',
  },
  {
    id: 20,
    channel: 'text',
    from: '2‑Factor Code',
    text: "Your verification code is 884213. Don't share this code with anyone.",
    hl: "Don't share this code",
    answer: 'legit',
    why: 'A code you requested is normal — the scam is when someone calls asking you to read it out.',
  },
  {
    id: 21,
    channel: 'email',
    from: 'PayPal',
    text: 'Someone sent you $500! Click to accept before it expires: pay-pal.cash/claim',
    hl: 'pay-pal.cash/claim',
    answer: 'sketchy',
    why: "You don't “claim” money you weren't expecting through a sketchy look‑alike link.",
  },
  {
    id: 22,
    channel: 'text',
    from: 'Food Delivery',
    text: 'Your order is 5 minutes away! Track your driver live in the app.',
    hl: 'in the app',
    answer: 'legit',
    why: 'A delivery update that points you back to the app you ordered from is fine.',
  },
  {
    id: 23,
    channel: 'email',
    from: 'Walmart Rewards',
    text: 'SHOPPER SELECTED: Claim your FREE $750 reward — just finish this quick 3‑question survey!',
    hl: 'FREE $750 reward',
    answer: 'sketchy',
    why: '“Free reward, just take this survey” funnels you toward handing over personal info.',
  },
  {
    id: 24,
    channel: 'text',
    from: 'Lincoln Elementary',
    text: 'Reminder: early dismissal tomorrow at 1 PM due to the weather forecast.',
    hl: 'early dismissal tomorrow',
    answer: 'legit',
    why: 'An informational alert from a school you know, with nothing to click or pay, is normal.',
  },
  {
    id: 25,
    channel: 'text',
    from: 'Crypto Coach',
    text: 'Double your Bitcoin in 24 hours! Send to this wallet to start earning today.',
    hl: 'Double your Bitcoin',
    answer: 'sketchy',
    why: "Guaranteed doubling is impossible. Send crypto to a stranger and it's just gone.",
  },
  {
    id: 26,
    channel: 'email',
    from: 'Spotify',
    text: "Here's your receipt — Premium, $10.99. Manage your plan any time in Account settings.",
    hl: 'Account settings',
    answer: 'legit',
    why: 'A receipt for a subscription you actually have, pointing to your own settings, is routine.',
  },

  /* ---- batch 2: 50-card deck. Trickier (but fair) legit cards. ---- */
  {
    id: 27,
    channel: 'text',
    from: 'Verizon',
    text: 'Your bill is overdue. Avoid service cutoff today — pay here: vzw-secure-pay.com',
    hl: 'vzw-secure-pay.com',
    answer: 'sketchy',
    why: 'Real carriers send you to their official app or site, not a look‑alike pay link.',
  },
  {
    id: 28,
    channel: 'email',
    from: 'DocuSign',
    text: 'You have a document to sign. Review and verify your login first: docusign-verify.net',
    hl: 'docusign-verify.net',
    answer: 'sketchy',
    why: '“Verify your login” plus an odd domain is the tell — open the real site directly.',
  },
  {
    id: 29,
    channel: 'text',
    from: 'Toll Service',
    text: 'You have an unpaid toll of $6.99. Pay now to avoid a $50 late fee: ezpass-toll.info',
    hl: 'ezpass-toll.info',
    answer: 'sketchy',
    why: 'Toll‑by‑text scams pair a tiny fee with a big threat and a fake domain.',
  },
  {
    id: 30,
    channel: 'marketplace',
    from: 'Buyer · Phone listing',
    text: "I'll buy it now! Send me your Venmo and I'll Zelle the deposit, then you ship first.",
    hl: 'ship first',
    answer: 'sketchy',
    why: 'Ship‑first, mixed‑app payment requests are how marketplace buyers vanish with your item.',
  },
  {
    id: 31,
    channel: 'job',
    from: 'HR · Remote Co',
    text: "You're hired! Send a photo of your ID and your bank login so we can set up payroll.",
    hl: 'bank login',
    answer: 'sketchy',
    why: 'No employer needs your bank login. Payroll uses account numbers, never your password.',
  },
  {
    id: 32,
    channel: 'email',
    from: 'Microsoft 365',
    text: "Unusual sign‑in detected. Confirm it's you in 15 minutes or your mailbox locks: m365-alert.co",
    hl: '15 minutes',
    answer: 'sketchy',
    why: 'A countdown plus a fake domain means phishing. Real alerts live inside your account.',
  },
  {
    id: 33,
    channel: 'text',
    from: 'Amazon',
    text: 'Your account is on hold. Verify your payment to release your recent order: amzn-billing.help',
    hl: 'amzn-billing.help',
    answer: 'sketchy',
    why: "Amazon won't text you a billing link from a random look‑alike domain.",
  },
  {
    id: 34,
    channel: 'bank',
    from: 'Chase Alert',
    text: "Did you spend $812 at BestBuy? Reply NO and we'll text you a link to lock your card.",
    hl: 'text you a link',
    answer: 'sketchy',
    why: 'A real fraud alert tells you to call the number on your card — not to tap a texted link.',
  },
  {
    id: 35,
    channel: 'email',
    from: 'Google',
    text: 'Your storage is full! Reactivate now with a one‑time $1.99 verification charge: g-storage.co',
    hl: '$1.99 verification charge',
    answer: 'sketchy',
    why: 'A “tiny verification charge” is a trick to capture your card. Google never does this.',
  },
  {
    id: 36,
    channel: 'text',
    from: 'Unknown Number',
    text: "Grandma, I'm in trouble and need $500 for bail. Please don't tell mom and dad.",
    hl: "don't tell mom and dad",
    answer: 'sketchy',
    why: 'Secrecy plus urgent money is the grandparent scam. Hang up and call them directly.',
  },
  {
    id: 37,
    channel: 'email',
    from: 'LinkedIn',
    text: 'A recruiter wants you! Unlock the offer by paying a $15 background-check fee.',
    hl: '$15 background-check fee',
    answer: 'sketchy',
    why: 'Legit recruiters never charge you an upfront fee to “unlock” a job.',
  },
  {
    id: 38,
    channel: 'text',
    from: 'Bank of America',
    text: 'ALERT: your account is suspended. Restore access immediately: bofa-secure-login.com',
    hl: 'bofa-secure-login.com',
    answer: 'sketchy',
    why: '“Suspended — click to restore” with a look‑alike domain is classic bank phishing.',
  },

  {
    id: 39,
    channel: 'bank',
    from: 'Chase',
    text: 'We blocked a $640 charge we flagged as fraud. If this was you, reply YES or call the number on your card.',
    hl: 'call the number on your card',
    answer: 'legit',
    why: "It points you to the number on your card and asks for no secrets — that's how a real alert behaves.",
  },
  {
    id: 40,
    channel: 'email',
    from: 'IRS.gov',
    text: 'Your tax refund has been processed. Track its status any time at irs.gov/refunds.',
    hl: 'irs.gov/refunds',
    answer: 'legit',
    why: 'It points to the real .gov site, asks for nothing, and makes no threats — a normal update.',
  },
  {
    id: 41,
    channel: 'package',
    from: 'UPS',
    text: 'Your delivery needs a signature. Pick a new date in the UPS app or at ups.com.',
    hl: 'in the UPS app',
    answer: 'legit',
    why: 'It sends you to the official app or site with no fee and no login link — routine.',
  },
  {
    id: 42,
    channel: 'email',
    from: 'PayPal',
    text: "You sent $24.00 to Corner Coffee. Didn't make this? Report it from your PayPal Activity page.",
    hl: 'PayPal Activity page',
    answer: 'legit',
    why: 'A receipt that points back to your own account page, with no link to click, is normal.',
  },
  {
    id: 43,
    channel: 'bank',
    from: 'Wells Fargo',
    text: 'Your monthly statement is ready. View it by signing in at wellsfargo.com or in the app.',
    hl: 'wellsfargo.com',
    answer: 'legit',
    why: '“Statement ready, sign in normally” with the real domain and no urgency is routine.',
  },
  {
    id: 44,
    channel: 'text',
    from: "Doctor's Office",
    text: 'Your lab results are in. Log in to the patient portal to view them.',
    hl: 'patient portal',
    answer: 'legit',
    why: 'Health updates that send you to log in normally, with nothing to pay, are standard.',
  },
  {
    id: 45,
    channel: 'email',
    from: 'United Airlines',
    text: 'Check‑in for flight UA482 opens in 24 hours. Check in on the app or at the airport.',
    hl: 'opens in 24 hours',
    answer: 'legit',
    why: 'A travel reminder with normal options and nothing to “verify” or pay is fine.',
  },
  {
    id: 46,
    channel: 'text',
    from: 'Corner Pharmacy',
    text: 'Your prescription is ready for pickup at the Main St location.',
    hl: 'ready for pickup',
    answer: 'legit',
    why: 'A simple pickup notice that asks for nothing is routine.',
  },
  {
    id: 47,
    channel: 'email',
    from: 'City Utilities',
    text: 'Scheduled maintenance may interrupt power on June 12, 1–3 PM. No action needed.',
    hl: 'Scheduled maintenance',
    answer: 'legit',
    why: 'An informational notice with a specific window and nothing to click is normal.',
  },
  {
    id: 48,
    channel: 'text',
    from: 'Your Bank',
    text: 'Your one‑time code is 503118. We will never ask you to share it.',
    hl: 'never ask you to share it',
    answer: 'legit',
    why: 'Codes you requested are normal — the scam is anyone asking you to read it aloud.',
  },
  {
    id: 49,
    channel: 'email',
    from: 'School District',
    text: 'Report cards are now available in the parent portal.',
    hl: 'parent portal',
    answer: 'legit',
    why: 'Pointing you to a portal you already use, with nothing to buy, is routine.',
  },
  {
    id: 50,
    channel: 'marketplace',
    from: 'Buyer · Desk listing',
    text: 'Still available? I can pay cash on pickup tomorrow afternoon if that works.',
    hl: 'cash on pickup',
    answer: 'legit',
    why: 'Cash on local pickup and normal questions — a real buyer.',
  },
]
