const rawFoodCards = [
  {
    id: 'food-001',
    claim: 'Bananas are berries.',
    answer: 'fresh',
    explanation: 'Botanically, bananas qualify as berries because they develop from one flower with one ovary.',
    category: 'Botany',
    highlight: 'Bananas are berries',
  },
  {
    id: 'food-002',
    claim: 'Strawberries are true botanical berries.',
    answer: 'fake',
    explanation: 'Strawberries are accessory fruits; their tiny outside seeds are actually individual fruits.',
    category: 'Botany',
    highlight: 'true botanical berries',
  },
  {
    id: 'food-003',
    claim: 'Honey can stay edible for a very long time when sealed and stored properly.',
    answer: 'fresh',
    explanation: 'Honey is low in water and acidic, which helps it resist spoilage when kept sealed.',
    category: 'Pantry',
    highlight: 'very long time',
  },
  {
    id: 'food-004',
    claim: 'Pineapples grow on trees.',
    answer: 'fake',
    explanation: 'Pineapples grow from low plants close to the ground, not from tree branches.',
    category: 'Growing',
    highlight: 'grow on trees',
  },
  {
    id: 'food-005',
    claim: 'Peanuts are legumes.',
    answer: 'fresh',
    explanation: 'Peanuts grow in pods and belong to the legume family, like beans and lentils.',
    category: 'Botany',
    highlight: 'Peanuts are legumes',
  },
  {
    id: 'food-006',
    claim: 'White chocolate contains cocoa solids.',
    answer: 'fake',
    explanation: 'White chocolate uses cocoa butter, but it does not contain the brown cocoa solids found in chocolate.',
    category: 'Sweets',
    highlight: 'cocoa solids',
  },
  {
    id: 'food-007',
    claim: 'Cashews grow attached to a fruit.',
    answer: 'fresh',
    explanation: 'Cashew nuts grow below the cashew apple, a colorful fruit-like stem.',
    category: 'Growing',
    highlight: 'attached to a fruit',
  },
  {
    id: 'food-008',
    claim: 'Carrots were always orange.',
    answer: 'fake',
    explanation: 'Carrots have grown in several colors, including purple, yellow, white, and red.',
    category: 'History',
    highlight: 'always orange',
  },
  {
    id: 'food-009',
    claim: 'Tomatoes are botanically fruits.',
    answer: 'fresh',
    explanation: 'Tomatoes develop from flowers and contain seeds, so botanically they are fruits.',
    category: 'Botany',
    highlight: 'botanically fruits',
  },
  {
    id: 'food-010',
    claim: 'Fortune cookies were invented in China.',
    answer: 'fake',
    explanation: 'Modern fortune cookies became popular in the United States, with roots often linked to Japanese American bakers.',
    category: 'History',
    highlight: 'invented in China',
  },
  {
    id: 'food-011',
    claim: 'Vanilla comes from an orchid.',
    answer: 'fresh',
    explanation: 'Vanilla beans are seed pods from vanilla orchids.',
    category: 'Spices',
    highlight: 'an orchid',
  },
  {
    id: 'food-012',
    claim: 'Cocoa beans grow loose on tree branches like cherries.',
    answer: 'fake',
    explanation: 'Cacao trees produce large pods, and the cocoa beans are found inside those pods.',
    category: 'Sweets',
    highlight: 'loose on tree branches',
  },
  {
    id: 'food-013',
    claim: 'Rice grows naturally as tiny dry grains in bags.',
    answer: 'fake',
    explanation: 'Rice grows on grass-like plants and is harvested, dried, and milled before it reaches bags.',
    category: 'Growing',
    highlight: 'dry grains in bags',
  },
  {
    id: 'food-014',
    claim: 'Avocados are fruits.',
    answer: 'fresh',
    explanation: 'Avocados develop from flowers and contain a seed, making them fruits botanically.',
    category: 'Botany',
    highlight: 'Avocados are fruits',
  },
  {
    id: 'food-015',
    claim: 'Cinnamon is made from tree bark.',
    answer: 'fresh',
    explanation: 'Cinnamon comes from the inner bark of trees in the Cinnamomum genus.',
    category: 'Spices',
    highlight: 'tree bark',
  },
  {
    id: 'food-016',
    claim: 'Saffron is usually made from dried tulip petals.',
    answer: 'fake',
    explanation: 'Saffron threads are the dried stigmas of crocus flowers, not tulip petals.',
    category: 'Spices',
    highlight: 'tulip petals',
  },
  {
    id: 'food-017',
    claim: 'Potatoes are roots.',
    answer: 'fake',
    explanation: 'Potatoes are stem tubers, which are swollen underground stems.',
    category: 'Botany',
    highlight: 'Potatoes are roots',
  },
  {
    id: 'food-018',
    claim: 'Broccoli is made of flower buds.',
    answer: 'fresh',
    explanation: 'The broccoli crown is a cluster of unopened flower buds and stems.',
    category: 'Botany',
    highlight: 'flower buds',
  },
  {
    id: 'food-019',
    claim: 'Watermelons are mostly water.',
    answer: 'fresh',
    explanation: 'Watermelon flesh is roughly nine-tenths water, which explains its juicy crunch.',
    category: 'Fruit Facts',
    highlight: 'mostly water',
  },
  {
    id: 'food-020',
    claim: 'Mushrooms are plants.',
    answer: 'fake',
    explanation: 'Mushrooms are fungi, a separate kingdom from plants.',
    category: 'Fungi',
    highlight: 'plants',
  },
  {
    id: 'food-021',
    claim: 'Coffee beans are actually seeds.',
    answer: 'fresh',
    explanation: 'Coffee beans are the seeds inside coffee cherries.',
    category: 'Drinks',
    highlight: 'actually seeds',
  },
  {
    id: 'food-022',
    claim: 'Black pepper comes from dried peppercorn berries.',
    answer: 'fresh',
    explanation: 'Peppercorns are small fruits from the pepper plant that are dried for spice.',
    category: 'Spices',
    highlight: 'peppercorn berries',
  },
  {
    id: 'food-023',
    claim: 'Bell peppers are vegetables in botanical terms.',
    answer: 'fake',
    explanation: 'Botanically, bell peppers are fruits because they form from flowers and contain seeds.',
    category: 'Botany',
    highlight: 'vegetables in botanical terms',
  },
  {
    id: 'food-024',
    claim: 'Any corn kernel will pop into popcorn if you heat it.',
    answer: 'fake',
    explanation: 'Popcorn comes from specific varieties with the right shell and moisture balance.',
    category: 'Snacks',
    highlight: 'Any corn kernel',
  },
  {
    id: 'food-025',
    claim: 'Almonds grow inside fleshy fruits related to peaches.',
    answer: 'fresh',
    explanation: 'Almonds are seeds of drupes, and almond trees are relatives of peaches and plums.',
    category: 'Growing',
    highlight: 'related to peaches',
  },
  {
    id: 'food-026',
    claim: 'Pickles are always made from cucumbers.',
    answer: 'fake',
    explanation: 'Many foods can be pickled, including carrots, onions, peppers, and eggs.',
    category: 'Pantry',
    highlight: 'always made from cucumbers',
  },
  {
    id: 'food-027',
    claim: 'Ketchup was once commonly made with mushrooms.',
    answer: 'fresh',
    explanation: 'Before tomato ketchup became dominant, mushroom ketchup was popular in Britain.',
    category: 'History',
    highlight: 'mushrooms',
  },
  {
    id: 'food-028',
    claim: 'A coconut is a mammal-made nut.',
    answer: 'fake',
    explanation: 'Coconuts come from palm trees; they are plant fruits, not anything made by mammals.',
    category: 'Botany',
    highlight: 'mammal-made nut',
  },
  {
    id: 'food-029',
    claim: 'Cranberries can bounce when they are firm and fresh.',
    answer: 'fresh',
    explanation: 'Fresh cranberries have air pockets that can make them bounce.',
    category: 'Fruit Facts',
    highlight: 'can bounce',
  },
  {
    id: 'food-030',
    claim: 'Most wasabi paste gets its heat from sweet vanilla beans.',
    answer: 'fake',
    explanation: 'Many wasabi-style pastes use horseradish and mustard for heat, not vanilla.',
    category: 'Condiments',
    highlight: 'vanilla beans',
  },
  {
    id: 'food-031',
    claim: 'Cheddar cheese is naturally bright orange.',
    answer: 'fake',
    explanation: 'Cheddar is naturally pale to yellow; orange cheddar usually gets color from annatto.',
    category: 'Dairy',
    highlight: 'naturally bright orange',
  },
  {
    id: 'food-032',
    claim: 'Pistachios grow in clusters on trees.',
    answer: 'fresh',
    explanation: 'Pistachios grow on trees in grape-like clusters.',
    category: 'Growing',
    highlight: 'clusters on trees',
  },
  {
    id: 'food-033',
    claim: 'Eggplants are called eggplants because they grow from bird eggs.',
    answer: 'fake',
    explanation: 'The name came from small white varieties that looked egg-like, not from bird eggs.',
    category: 'Botany',
    highlight: 'bird eggs',
  },
  {
    id: 'food-034',
    claim: 'Lemons float because they contain helium.',
    answer: 'fake',
    explanation: 'Lemons may float due to density and their rind structure, not helium.',
    category: 'Kitchen Science',
    highlight: 'contain helium',
  },
  {
    id: 'food-035',
    claim: 'Yeast is alive.',
    answer: 'fresh',
    explanation: 'Yeast is a living fungus that helps dough rise by producing carbon dioxide.',
    category: 'Baking',
    highlight: 'Yeast is alive',
  },
  {
    id: 'food-036',
    claim: 'Bread rises because yeast makes oxygen bubbles.',
    answer: 'fake',
    explanation: 'Yeast produces carbon dioxide gas, which creates bubbles in dough.',
    category: 'Baking',
    highlight: 'oxygen bubbles',
  },
  {
    id: 'food-037',
    claim: 'Rhubarb leaves are the part commonly used in pies.',
    answer: 'fake',
    explanation: 'Rhubarb stalks are used in pies; the leaves are not used as food.',
    category: 'Baking',
    highlight: 'leaves',
  },
  {
    id: 'food-038',
    claim: 'Gelatin can come from collagen.',
    answer: 'fresh',
    explanation: 'Gelatin is made by processing collagen from animal connective tissues.',
    category: 'Kitchen Science',
    highlight: 'collagen',
  },
  {
    id: 'food-039',
    claim: 'All pasta was invented in modern Italy.',
    answer: 'fake',
    explanation: 'Noodle-like foods have long histories in several regions, including Asia and the Mediterranean.',
    category: 'History',
    highlight: 'All pasta',
  },
  {
    id: 'food-040',
    claim: 'Maple syrup comes from tree sap.',
    answer: 'fresh',
    explanation: 'Maple syrup is made by collecting and boiling sap from maple trees.',
    category: 'Pantry',
    highlight: 'tree sap',
  },
  {
    id: 'food-041',
    claim: 'Olives are fruits.',
    answer: 'fresh',
    explanation: 'Olives are drupes, a type of fruit with a pit.',
    category: 'Botany',
    highlight: 'Olives are fruits',
  },
  {
    id: 'food-042',
    claim: 'Tofu is made from wheat milk.',
    answer: 'fake',
    explanation: 'Tofu is made from soy milk that is coagulated and pressed.',
    category: 'Ingredients',
    highlight: 'wheat milk',
  },
  {
    id: 'food-043',
    claim: 'Quinoa seeds are cooked and eaten like grains.',
    answer: 'fresh',
    explanation: 'Quinoa is a seed, but it is often cooked and used like a grain.',
    category: 'Ingredients',
    highlight: 'like grains',
  },
  {
    id: 'food-044',
    claim: 'Ginger is commonly used as a plant stem called a rhizome.',
    answer: 'fresh',
    explanation: 'The edible part of ginger is a rhizome, a kind of underground stem.',
    category: 'Spices',
    highlight: 'rhizome',
  },
  {
    id: 'food-045',
    claim: 'Cucumbers are root vegetables.',
    answer: 'fake',
    explanation: 'Cucumbers grow from flowers and contain seeds, so botanically they are fruits.',
    category: 'Botany',
    highlight: 'root vegetables',
  },
  {
    id: 'food-046',
    claim: 'Brown sugar is just white sugar painted with cocoa.',
    answer: 'fake',
    explanation: 'Brown sugar gets its color and flavor from molasses, not cocoa paint.',
    category: 'Baking',
    highlight: 'painted with cocoa',
  },
  {
    id: 'food-047',
    claim: 'Sea salt and table salt are both mostly sodium chloride.',
    answer: 'fresh',
    explanation: 'Both are mainly sodium chloride, though texture and trace minerals can differ.',
    category: 'Kitchen Science',
    highlight: 'sodium chloride',
  },
  {
    id: 'food-048',
    claim: 'Marshmallows originally used a plant called mallow.',
    answer: 'fresh',
    explanation: 'Early marshmallow sweets used sap from the marsh mallow plant.',
    category: 'History',
    highlight: 'mallow',
  },
  {
    id: 'food-049',
    claim: 'The holes in Swiss-style cheese are caused by tiny drills.',
    answer: 'fake',
    explanation: 'The holes form from gas bubbles produced by bacteria during cheesemaking.',
    category: 'Dairy',
    highlight: 'tiny drills',
  },
  {
    id: 'food-050',
    claim: 'Green, black, and oolong teas can come from the same plant species.',
    answer: 'fresh',
    explanation: 'They can all come from Camellia sinensis; processing creates the differences.',
    category: 'Drinks',
    highlight: 'same plant species',
  },
]

export const foodCards = rawFoodCards.map((card, index) => ({
  difficulty: index < 16 ? 'easy' : index < 36 ? 'medium' : 'hard',
  confidence: 'high',
  sourceNote: 'Launch deck fact checked for clear non-medical food trivia.',
  ...card,
}))
