const rawScamCards = [
  {
    id: 'scam-001',
    claim: 'Your bank texts: “We noticed suspicious activity. Verify your password now or access stops.”',
    answer: 'fake',
    explanation: 'Banks do not ask for passwords by text. Urgent “verify now” messages are phishing bait.',
    category: 'Bank Alert',
    highlight: 'Verify your password',
  },
  {
    id: 'scam-002',
    claim: 'Your dentist texts: “Appointment tomorrow at 2 PM. Reply C to confirm.”',
    answer: 'fresh',
    explanation: 'A simple appointment reminder that asks for no money or secrets is usually legitimate.',
    category: 'Text Message',
    highlight: 'Reply C to confirm',
  },
  {
    id: 'scam-003',
    claim: 'A buyer says they will overpay for your couch and asks you to refund the extra money.',
    answer: 'fake',
    explanation: 'Overpayment plus “send the difference back” is a classic marketplace scam.',
    category: 'Marketplace',
    highlight: 'refund the extra',
  },
  {
    id: 'scam-004',
    claim: 'A package notice says to track your shipment in the official carrier app.',
    answer: 'fresh',
    explanation: 'Pointing you back to an official app, without a payment link, is a safer pattern.',
    category: 'Package Alert',
    highlight: 'official carrier app',
  },
  {
    id: 'scam-005',
    claim: 'A remote job offer says they will send a check so you can buy equipment from their vendor.',
    answer: 'fake',
    explanation: 'Fake-check job scams often ask you to deposit a check and send money onward.',
    category: 'Job Offer',
    highlight: 'send a check',
  },
  {
    id: 'scam-006',
    claim: 'Your credit card app says your monthly statement is ready and asks you to sign in normally.',
    answer: 'fresh',
    explanation: 'A calm notice that sends you to your normal sign-in path is usually fine.',
    category: 'Bank Alert',
    highlight: 'sign in normally',
  },
  {
    id: 'scam-007',
    claim: 'A message says you won a gift card from a contest you never entered.',
    answer: 'fake',
    explanation: 'Surprise prizes with claim links are designed to collect personal or payment details.',
    category: 'Prize',
    highlight: 'contest you never entered',
  },
  {
    id: 'scam-008',
    claim: 'Your library emails that a hold is ready and says to bring your library card.',
    answer: 'fresh',
    explanation: 'A pickup notice with no payment link or password request is normal.',
    category: 'Email',
    highlight: 'bring your library card',
  },
  {
    id: 'scam-009',
    claim: 'A caller says they are from support and asks you to read them your one-time code.',
    answer: 'fake',
    explanation: 'One-time codes should not be shared. Asking for one is a profile takeover trick.',
    category: 'Code Scam',
    highlight: 'one-time code',
  },
  {
    id: 'scam-010',
    claim: 'A delivery app says your food order is five minutes away and to track it in the app.',
    answer: 'fresh',
    explanation: 'A delivery update from an app you used, with no extra payment request, is routine.',
    category: 'Delivery',
    highlight: 'track it in the app',
  },
  {
    id: 'scam-011',
    claim: 'A “boss” emails asking you to buy gift cards and text the codes quietly.',
    answer: 'fake',
    explanation: 'Secret gift-card requests from a boss are a common workplace scam.',
    category: 'Workplace',
    highlight: 'text the codes',
  },
  {
    id: 'scam-012',
    claim: 'A school district sends an early dismissal alert with no links or payment request.',
    answer: 'fresh',
    explanation: 'Informational alerts from known organizations are usually safe when they ask for nothing sensitive.',
    category: 'School Alert',
    highlight: 'no links',
  },
  {
    id: 'scam-013',
    claim: 'A toll text threatens a big late fee unless you pay a small charge through a strange link.',
    answer: 'fake',
    explanation: 'Small fees plus big threats and odd links are common toll scam signals.',
    category: 'Toll Notice',
    highlight: 'strange link',
  },
  {
    id: 'scam-014',
    claim: 'A pharmacy texts that your prescription is ready for pickup at your usual location.',
    answer: 'fresh',
    explanation: 'A simple pickup notice from a place you use is low-risk when it asks for nothing else.',
    category: 'Health Notice',
    highlight: 'ready for pickup',
  },
  {
    id: 'scam-015',
    claim: 'A message from a new number says it is your child and urgently needs money today.',
    answer: 'fake',
    explanation: 'New-number emergency money requests are impersonation scams. Verify another way first.',
    category: 'Impersonation',
    highlight: 'urgently needs money',
  },
  {
    id: 'scam-016',
    claim: 'A streaming receipt says you can manage your plan inside app settings.',
    answer: 'fresh',
    explanation: 'A normal receipt pointing to app settings, not a forced link, is usually legitimate.',
    category: 'Receipt',
    highlight: 'app settings',
  },
  {
    id: 'scam-017',
    claim: 'A fake tax notice demands payment in gift cards to avoid arrest.',
    answer: 'fake',
    explanation: 'Government agencies do not demand gift cards or threaten arrest by text.',
    category: 'Tax Scam',
    highlight: 'gift cards',
  },
  {
    id: 'scam-018',
    claim: 'A local buyer asks to meet in a public place and pay cash at pickup.',
    answer: 'fresh',
    explanation: 'Public meetup plus payment at pickup is a normal marketplace pattern.',
    category: 'Marketplace',
    highlight: 'pay cash at pickup',
  },
  {
    id: 'scam-019',
    claim: 'A crypto message promises to double your money in 24 hours if you send crypto first.',
    answer: 'fake',
    explanation: 'Guaranteed crypto doubling is not real. Sending crypto first is the trap.',
    category: 'Crypto',
    highlight: 'double your money',
  },
  {
    id: 'scam-020',
    claim: 'A bank alert says to call the number printed on your card if a charge was not yours.',
    answer: 'fresh',
    explanation: 'Using the number on your own card is a trusted path and avoids suspicious links.',
    category: 'Bank Alert',
    highlight: 'printed on your card',
  },
]

export const scamCards = rawScamCards.map((card, index) => ({
  difficulty: index < 7 ? 'easy' : index < 15 ? 'medium' : 'hard',
  confidence: 'high',
  sourceNote: 'Launch deck uses common scam-pattern education, not legal or financial advice.',
  ...card,
}))
