/* ============================================================
   Gut Check — Science Snacks deck (binary: True / Nope).
   Bite-size science, curated and paraphrased with real sources. No medical or
   health claims. Wikipedia text is CC BY-SA; these are short paraphrases.
   answer: 'true' (real) | 'false' (myth / not true).
   ============================================================ */

const WIKI = 'CC BY-SA 4.0'

const rawScienceSnacksCards = [
  { id: 'sci-001', category: 'Space', claim: 'Sound cannot travel through the vacuum of space.', highlight: 'cannot travel', answer: 'true', difficulty: 'easy', explanation: 'Sound needs a medium to travel through; space is nearly empty, so it can’t carry sound.', graphic: { type: 'emoji', value: '🔇' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Outer_space', sourceLicense: WIKI },
  { id: 'sci-002', category: 'Chemistry', claim: 'Diamond and graphite are both made of pure carbon.', highlight: 'pure carbon', answer: 'true', difficulty: 'medium', explanation: 'Same element, different arrangement of atoms — that’s why their properties differ so much.', graphic: { type: 'emoji', value: '💎' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Carbon', sourceLicense: WIKI },
  { id: 'sci-003', category: 'Physics', claim: 'Most of an atom is empty space.', highlight: 'empty space', answer: 'true', difficulty: 'medium', explanation: 'The nucleus is tiny compared with the atom; the electrons occupy a vast space around it.', graphic: { type: 'emoji', value: '⚛️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Atom', sourceLicense: WIKI },
  { id: 'sci-004', category: 'Space', claim: 'Sunlight takes about 8 minutes to reach Earth.', highlight: 'about 8 minutes', answer: 'true', difficulty: 'easy', explanation: 'Light covers the ~150 million km from the Sun to Earth in roughly 8 minutes 20 seconds.', graphic: { type: 'emoji', value: '☀️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Sunlight', sourceLicense: WIKI },
  { id: 'sci-005', category: 'Space', claim: 'A teaspoon of neutron-star material would weigh billions of tons.', highlight: 'billions of tons', answer: 'true', difficulty: 'hard', explanation: 'Neutron stars are so dense that a sugar-cube-sized piece would weigh about as much as a mountain.', graphic: { type: 'emoji', value: '🌟' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Neutron_star', sourceLicense: WIKI },
  { id: 'sci-006', category: 'Physics', claim: 'Most metals expand when they are heated.', highlight: 'expand when they are heated', answer: 'true', difficulty: 'easy', explanation: 'Heat makes atoms vibrate more and take up slightly more room — that’s thermal expansion.', graphic: { type: 'emoji', value: '🌡️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Thermal_expansion', sourceLicense: WIKI },
  { id: 'sci-007', category: 'Physics', claim: 'Helium makes your voice sound higher because sound travels faster through it.', highlight: 'travels faster through it', answer: 'true', difficulty: 'medium', explanation: 'Sound moves faster in helium, which shifts the resonances of your voice upward.', graphic: { type: 'emoji', value: '🎈' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Helium', sourceLicense: WIKI },

  { id: 'sci-008', category: 'Materials', claim: 'Old windows are thicker at the bottom because glass slowly flows like a liquid.', highlight: 'slowly flows like a liquid', answer: 'false', difficulty: 'medium', explanation: 'A myth — glass is an amorphous solid. Old panes vary because of how they were made.', graphic: { type: 'emoji', value: '🪟' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Glass', sourceLicense: WIKI },
  { id: 'sci-009', category: 'Space', claim: 'The far side of the Moon never gets any sunlight.', highlight: 'never gets any sunlight', answer: 'false', difficulty: 'medium', explanation: 'The “dark side” still gets sunlight — we just never see it from Earth.', graphic: { type: 'emoji', value: '🌙' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Far_side_of_the_Moon', sourceLicense: WIKI },
  { id: 'sci-010', category: 'Earth', claim: 'Seasons happen because Earth is closer to the Sun in summer.', highlight: 'closer to the Sun in summer', answer: 'false', difficulty: 'medium', explanation: 'Seasons come from Earth’s tilted axis, not its distance from the Sun.', graphic: { type: 'emoji', value: '🍂' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Season', sourceLicense: WIKI },
  { id: 'sci-011', category: 'Physics', claim: 'A penny dropped from a skyscraper could kill a pedestrian below.', highlight: 'could kill a pedestrian', answer: 'false', difficulty: 'medium', explanation: 'A penny’s terminal velocity is too low to be deadly — it would sting at most.', graphic: { type: 'emoji', value: '🪙' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Terminal_velocity', sourceLicense: WIKI },
  { id: 'sci-012', category: 'Biology', claim: 'Humans have exactly five senses.', highlight: 'exactly five senses', answer: 'false', difficulty: 'easy', explanation: 'We have more — including balance and the sense of where our body is (proprioception).', graphic: { type: 'emoji', value: '🖐️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Sense', sourceLicense: WIKI },
  { id: 'sci-013', category: 'Chemistry', claim: 'Perfectly pure water is an excellent conductor of electricity.', highlight: 'excellent conductor', answer: 'false', difficulty: 'hard', explanation: 'Pure water barely conducts; it’s the dissolved minerals and salts that carry current.', graphic: { type: 'emoji', value: '💧' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Purified_water', sourceLicense: WIKI },
  { id: 'sci-014', category: 'Earth', claim: 'Mount Everest is the point on Earth closest to outer space.', highlight: 'closest to outer space', answer: 'false', difficulty: 'hard', explanation: 'Because Earth bulges at the equator, the summit of Chimborazo is actually closer to space.', graphic: { type: 'emoji', value: '🏔️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Chimborazo', sourceLicense: WIKI },
  { id: 'sci-015', category: 'Chemistry', claim: 'Water expands when it freezes into ice.', highlight: 'expands when it freezes', answer: 'true', difficulty: 'easy', explanation: 'Ice is less dense than liquid water, which is why it floats and pipes can burst.', graphic: { type: 'emoji', value: '🧊' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Properties_of_water', sourceLicense: WIKI },
  { id: 'sci-016', category: 'Physics', claim: 'Nothing can travel faster than light in a vacuum.', highlight: 'faster than light', answer: 'true', difficulty: 'medium', explanation: 'The speed of light in a vacuum is the universe’s ultimate speed limit.', graphic: { type: 'emoji', value: '💡' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Speed_of_light', sourceLicense: WIKI },
  { id: 'sci-017', category: 'Physics', claim: 'Hot air rises because it is less dense than cold air.', highlight: 'less dense', answer: 'true', difficulty: 'easy', explanation: 'Warmer air spreads out, becomes lighter for its volume, and floats upward — convection.', graphic: { type: 'emoji', value: '🎈' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Convection', sourceLicense: WIKI },
  { id: 'sci-018', category: 'Chemistry', claim: 'Rust forms when iron reacts with oxygen and water.', highlight: 'oxygen and water', answer: 'true', difficulty: 'easy', explanation: 'That reaction produces iron oxide — the flaky orange rust we know.', graphic: { type: 'emoji', value: '🔩' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Rust', sourceLicense: WIKI },
  { id: 'sci-019', category: 'Earth', claim: 'The Earth’s inner core is solid.', highlight: 'inner core is solid', answer: 'true', difficulty: 'medium', explanation: 'Despite the extreme heat, immense pressure keeps the inner core solid iron-nickel.', graphic: { type: 'emoji', value: '🌍' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Earth%27s_inner_core', sourceLicense: WIKI },
  { id: 'sci-020', category: 'Space', claim: 'The Sun burns by combustion, like a campfire.', highlight: 'by combustion', answer: 'false', difficulty: 'medium', explanation: 'The Sun shines from nuclear fusion, not burning/combustion.', graphic: { type: 'emoji', value: '☀️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Sun', sourceLicense: WIKI },
  { id: 'sci-021', category: 'Physics', claim: 'A compass needle points to the true (geographic) North Pole.', highlight: 'true (geographic) North Pole', answer: 'false', difficulty: 'hard', explanation: 'It points to magnetic north, which differs from true north by the “declination.”', graphic: { type: 'emoji', value: '🧭' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Magnetic_declination', sourceLicense: WIKI },
  { id: 'sci-022', category: 'Biology', claim: 'Humans evolved directly from chimpanzees.', highlight: 'directly from chimpanzees', answer: 'false', difficulty: 'medium', explanation: 'Humans and chimps share a common ancestor — we didn’t descend from modern chimps.', graphic: { type: 'emoji', value: '🐒' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Human_evolution', sourceLicense: WIKI },
  { id: 'sci-023', category: 'Physics', claim: 'Sound travels faster through air than through water.', highlight: 'faster through air', answer: 'false', difficulty: 'medium', explanation: 'Sound actually moves much faster in water than in air.', graphic: { type: 'emoji', value: '🌊' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Speed_of_sound', sourceLicense: WIKI },
  { id: 'sci-024', category: 'Physics', claim: 'Atoms are the smallest things and cannot be split.', highlight: 'cannot be split', answer: 'false', difficulty: 'medium', explanation: 'Atoms are made of protons, neutrons, and electrons — and those break down further.', graphic: { type: 'emoji', value: '⚛️' }, sourceName: 'Wikipedia', sourceUrl: 'https://en.wikipedia.org/wiki/Atom', sourceLicense: WIKI },
]

export const scienceSnacksCards = rawScienceSnacksCards.map((card) => ({
  ...card,
  deckId: 'science',
  answerType: 'binary',
  confidence: 'high',
  difficulty: card.difficulty || 'medium',
}))
